name: Document builder

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Determine container version
        run: echo DOCKER_IMAGE=$(cat .vscode/settings.json | python3 -c "import json, sys; print(json.load(sys.stdin)['vorlage-latex.buildcontainer'])") >> $GITHUB_ENV
      - name: Pull container image
        run: docker pull $DOCKER_IMAGE
      - name: Build PDF
        run: docker run --rm -v "$GITHUB_WORKSPACE/Latex:/latex" -u $(id -u ${USER}):$(id -g ${USER}) $DOCKER_IMAGE
      - name: Archive PDF
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: Latex/main.pdf
